#' create a vega treemap transform object
#'
#' https://vega.github.io/vega/docs/transforms/treemap/index.html
#' 
#' The **treemap** transform recursively subdivides area into rectangles with areas proportional to each node's associated value.
#' 
#' Internally, this transform processes a collection of special tree node objects generated by an upstream [nest](../nest) or [stratify](../stratify) transform. The original input data object can be accessed under the `data` field of these tree node objects. This transform uses the [d3-hierarchy library](https://github.com/d3/d3-hierarchy).
#' 
#'
#' @param type All transforms require a type property, specifying the name of the transform.
#' @param field Field The data field corresponding to a numeric value for the node. The sum of values for a node and all its descendants is available on the node object as the `value` property. This field determines the size of a node.
#' @param sort Compare A comparator for sorting sibling nodes. The inputs to the comparator are tree node objects, not input data objects.
#' @param method String The layout method to use. One of `squarify` (the default), `resquarify`, `binary`, `dice`, `slice`, or `slicedice`. The `resquarify` method will preserve relative node positions once an initial layout has been computed, even if node sizes change.
#' @param padding Number Sets both the _paddingInner_ and _paddingOuter_ parameters to the same value.
#' @param paddingInner Number The padding used to separate a node's adjacent children (default `0`).
#' @param paddingOuter Number The padding used to separate the edges of a parent node from its contained children (default `0`). Sets the _paddingTop_, _paddingRight_, _paddingBottom_ and _paddingLeft_ parameters to the same value.
#' @param paddingTop Number The padding used to separate the top edge of a node from its children.
#' @param paddingRight Number The padding used to separate the right edge of a node from its children.
#' @param paddingBottom Number The padding used to separate the bottom edge of a node from its children.
#' @param paddingLeft Number The padding used to separate the left edge of a node from its children.
#' @param ratio Number The target aspect ratio for the `squarify` or `resquarify` methods. The default is the golden ratio, φ = (1 + sqrt(5)) / 2.
#' @param round Boolean Indicates if node layout values should be rounded (default `false`).
#' @param size Number[] The size of the layout, provided as a [width, height] array.
#' @param as String[] The output fields at which to write the layout results. The default is `["x0", "y0", "x1", "y1", "depth", "children"]`, where `x0`, `y0`, `x1` and `y1` are the starting and ending layout coordinates for each segment, `depth` is the tree depth, and `children` is the count of a node's children in the tree.
#' @return a transform object
#' @export
vega_treemap_transform <- function(
  type,
  field=NULL,
  sort=NULL,
  method=NULL,
  padding=NULL,
  paddingInner=NULL,
  paddingOuter=NULL,
  paddingTop=NULL,
  paddingRight=NULL,
  paddingBottom=NULL,
  paddingLeft=NULL,
  ratio=NULL,
  round=NULL,
  size=NULL,
  as=NULL
) {
  args <- list(field=field, sort=sort, method=method, padding=padding, paddingInner=paddingInner, paddingOuter=paddingOuter, paddingTop=paddingTop, paddingRight=paddingRight, paddingBottom=paddingBottom, paddingLeft=paddingLeft, ratio=ratio, round=round, size=size, as=as)
  args <- args[!unlist(lapply(args, is.null))]

  is.vega_transform(args, error=TRUE)

  args
}
