#' create a vega tree transform object
#'
#' https://vega.github.io/vega/docs/transforms/tree/index.html
#' 
#' The **tree** transform computes a node-link diagram layout for hierarchical data. It supports both _cluster_ layouts (for example to create [dendrograms](http://en.wikipedia.org/wiki/Dendrogram)) and _tidy_ layouts (using the method of [Rheingold & Tilford](http://emr.cs.iit.edu/~reingold/tidier-drawings.pdf), as later corrected by [Buchheim _et al._](http://dirk.jivas.de/papers/buchheim02improving.pdf)). The coordinates `x` and `y` produced by the layout represent an arbitrary coordinate system; for example, you can treat x as an angle and y as a radius to produce a radial layout.
#' 
#' Internally, this transform processes a collection of special tree node objects generated by an upstream [nest](../nest) or [stratify](../stratify) transform. The original input data object can be accessed under the `data` field of these tree node objects. This transform uses the [d3-hierarchy library](https://github.com/d3/d3-hierarchy).
#' 
#' ## Example
#' 
#' {% include embed spec="tree" %}
#' 
#'
#' @param type All transforms require a type property, specifying the name of the transform.
#' @param field Field The data field corresponding to a numeric value for the node. The sum of values for a node and all its descendants is available on the node object as the `value` property.
#' @param sort Compare A comparator for sorting sibling nodes. The inputs to the comparator are tree node objects, not input data objects.
#' @param method String The layout method to use. One of `tidy` (the default) or `cluster`.
#' @param size Number[] The size of the layout, provided as a [width, height] array.
#' @param nodeSize Number[] The size of each node, provided as a [width, height] array.
#' @param as String[] The output fields at which to write the layout results. The default is `["x", "y", "depth", "children"]`, where `x` and `y` are the layout coordinates, `depth` is the tree depth, and `children` is the count of a node's children in the tree.
#' @return a {0} transform object
#' @export
vega_tree_transform <- function(
  type,
  field=NULL,
  sort=NULL,
  method=NULL,
  size=NULL,
  nodeSize=NULL,
  as=NULL,
) {
  args <- list(field=field, sort=sort, method=method, size=size, nodeSize=nodeSize, as=as)
  args <- args[!unlist(lapply(args, is.null))]

  is.vega_transform(args, error=TRUE)

  args
}
