#' create a vega resolvefilter transform object
#'
#' https://vega.github.io/vega/docs/transforms/resolvefilter/index.html
#' 
#' The **resolvefilter** transform uses the filter mask generated by a [crossfilter](../crossfilter) transform to efficiently generate filtered data streams. A single crossfilter instance can be used to support cross-filtering over multiple charts; the filtered data streams for each individual chart are generated by using one resolvefilter transform per chart.
#' 
#'
#' @param type All transforms require a type property, specifying the name of the transform.
#' @param filter Signal (required) A signal reference to a backing [crossfilter](../crossfilter) transform.
#' @param ignore Number (required) A bit mask indicating which fields in the crossfilter should be ignored. Each bit corresponds to a field and query in the crossfilter transform's _fields_ and _query_ arrays. If the corresponding bit is on, that field and query will be ignored when resolving the filter. All other queries must pass the filter for a tuple to be included down stream.
#' @return a transform object
#' @export
vega_resolvefilter_transform <- function(
  type,
  filter=NULL,
  ignore=NULL
) {
  args <- list(filter=filter, ignore=ignore)
  args <- args[!unlist(lapply(args, is.null))]

  is.vega_transform(args, error=TRUE)

  args
}
